export type IconFace = "search" |
"home" |
"account_circle" |
"settings" |
"done" |
"info" |
"check_circle" |
"delete" |
"shopping_cart" |
"visibility" |
"favorite" |
"logout" |
"description" |
"favorite_border" |
"lock" |
"schedule" |
"face" |
"language" |
"help_outline" |
"fingerprint" |
"manage_accounts" |
"filter_alt" |
"event" |
"thumb_up" |
"verified" |
"dashboard" |
"calendar_today" |
"login" |
"list" |
"visibility_off" |
"check_circle_outline" |
"date_range" |
"highlight_off" |
"help" |
"article" |
"question_answer" |
"paid" |
"task_alt" |
"lightbulb" |
"shopping_bag" |
"open_in_new" |
"perm_identity" |
"trending_up" |
"credit_card" |
"history" |
"account_balance" |
"delete_outline" |
"report_problem" |
"fact_check" |
"assignment" |
"verified_user" |
"arrow_right_alt" |
"star_rate" |
"account_balance_wallet" |
"autorenew" |
"view_list" |
"print" |
"work" |
"build" |
"analytics" |
"today" |
"store" |
"delete_forever" |
"admin_panel_settings" |
"savings" |
"room" |
"lock_open" |
"code" |
"grade" |
"update" |
"add_shopping_cart" |
"receipt" |
"watch_later" |
"power_settings_new" |
"contact_support" |
"pets" |
"done_all" |
"explore" |
"bookmark" |
"account_box" |
"reorder" |
"note_add" |
"bookmark_border" |
"shopping_basket" |
"pending_actions" |
"payment" |
"drag_indicator" |
"supervisor_account" |
"launch" |
"touch_app" |
"thumb_up_off_alt" |
"pending" |
"zoom_in" |
"assessment" |
"done_outline" |
"exit_to_app" |
"open_in_full" |
"leaderboard" |
"preview" |
"assignment_ind" |
"card_giftcard" |
"view_in_ar" |
"feedback" |
"work_outline" |
"timeline" |
"published_with_changes" |
"android" |
"swap_horiz" |
"assignment_turned_in" |
"dns" |
"sync_alt" |
"book" |
"flight_takeoff" |
"stars" |
"pan_tool" |
"accessibility" |
"bug_report" |
"label" |
"alarm" |
"gavel" |
"cached" |
"contact_page" |
"supervised_user_circle" |
"translate" |
"get_app" |
"space_dashboard" |
"edit_calendar" |
"extension" |
"add_task" |
"minimize" |
"record_voice_over" |
"flutter_dash" |
"accessibility_new" |
"thumb_down" |
"hourglass_empty" |
"trending_flat" |
"help_center" |
"sticky_note_2" |
"rule" |
"support" |
"dashboard_customize" |
"source" |
"find_in_page" |
"view_headline" |
"settings_applications" |
"close_fullscreen" |
"announcement" |
"loyalty" |
"group_work" |
"redeem" |
"tips_and_updates" |
"compare_arrows" |
"swap_vert" |
"restore" |
"sensors" |
"dangerous" |
"euro_symbol" |
"grading" |
"nightlight_round" |
"privacy_tip" |
"subject" |
"track_changes" |
"copyright" |
"table_view" |
"book_online" |
"arrow_circle_up" |
"https" |
"ads_click" |
"disabled_by_default" |
"query_builder" |
"bookmarks" |
"api" |
"toc" |
"build_circle" |
"perm_media" |
"input" |
"3d_rotation" |
"backup" |
"zoom_out" |
"settings_phone" |
"circle_notifications" |
"view_module" |
"arrow_circle_down" |
"open_with" |
"perm_contact_calendar" |
"swipe" |
"file_present" |
"card_membership" |
"label_important" |
"speaker_notes" |
"wysiwyg" |
"perm_phone_msg" |
"pageview" |
"integration_instructions" |
"upgrade" |
"arrow_circle_right" |
"trending_down" |
"g_translate" |
"class" |
"change_history" |
"production_quantity_limits" |
"accessible" |
"offline_bolt" |
"settings_accessibility" |
"model_training" |
"calendar_view_month" |
"expand" |
"aspect_ratio" |
"donut_large" |
"settings_backup_restore" |
"segment" |
"maximize" |
"bookmark_add" |
"schedule_send" |
"thumbs_up_down" |
"thumb_down_off_alt" |
"view_column" |
"alarm_on" |
"settings_ethernet" |
"view_agenda" |
"invert_colors" |
"theaters" |
"calendar_month" |
"important_devices" |
"opacity" |
"open_in_browser" |
"unpublished" |
"commute" |
"youtube_searched_for" |
"addchart" |
"no_accounts" |
"history_toggle_off" |
"view_week" |
"system_update_alt" |
"turned_in" |
"tour" |
"shop" |
"settings_input_antenna" |
"mark_as_unread" |
"bookmark_added" |
"arrow_circle_left" |
"hide_source" |
"flight_land" |
"contactless" |
"plagiarism" |
"not_started" |
"search_off" |
"saved_search" |
"assignment_late" |
"mediation" |
"donut_small" |
"view_carousel" |
"anchor" |
"question_mark" |
"highlight_alt" |
"turned_in_not" |
"settings_input_component" |
"remove_shopping_cart" |
"flaky" |
"fit_screen" |
"settings_remote" |
"all_inbox" |
"edit_off" |
"toll" |
"settings_voice" |
"lock_clock" |
"view_quilt" |
"assignment_return" |
"hourglass_full" |
"online_prediction" |
"camera_enhance" |
"pregnant_woman" |
"rocket_launch" |
"event_seat" |
"next_plan" |
"swap_horizontal_circle" |
"restore_from_trash" |
"add_to_drive" |
"percent" |
"accessible_forward" |
"view_sidebar" |
"calendar_view_week" |
"markunread_mailbox" |
"vertical_split" |
"tab" |
"dynamic_form" |
"settings_power" |
"hotel_class" |
"request_page" |
"try" |
"smart_button" |
"offline_pin" |
"card_travel" |
"remove_done" |
"calendar_view_day" |
"view_stream" |
"rowing" |
"outbox" |
"data_exploration" |
"compress" |
"outlet" |
"find_replace" |
"alarm_add" |
"chrome_reader_mode" |
"assignment_returned" |
"play_for_work" |
"settings_brightness" |
"gif" |
"http" |
"spellcheck" |
"backup_table" |
"credit_card_off" |
"wifi_protected_setup" |
"settings_overscan" |
"restore_page" |
"settings_input_composite" |
"quickreply" |
"comment_bank" |
"polymer" |
"view_day" |
"swap_vertical_circle" |
"new_label" |
"line_weight" |
"send_and_archive" |
"token" |
"batch_prediction" |
"cancel_schedule_send" |
"outbound" |
"generating_tokens" |
"horizontal_split" |
"settings_bluetooth" |
"picture_in_picture" |
"bookmark_remove" |
"code_off" |
"filter_alt_off" |
"balance" |
"flip_to_front" |
"shop_two" |
"currency_exchange" |
"perm_scan_wifi" |
"speaker_notes_off" |
"perm_data_setting" |
"eject" |
"settings_cell" |
"fax" |
"free_cancellation" |
"gif_box" |
"alarm_off" |
"settings_input_hdmi" |
"hourglass_disabled" |
"disabled_visible" |
"sensors_off" |
"app_blocking" |
"work_off" |
"line_style" |
"switch_access_shortcut" |
"shopping_cart_checkout" |
"perm_device_information" |
"picture_in_picture_alt" |
"subtitles_off" |
"update_disabled" |
"settings_input_svideo" |
"voice_over_off" |
"view_array" |
"flip_to_back" |
"rocket" |
"switch_access_shortcut_add" |
"lock_reset" |
"open_in_new_off" |
"all_out" |
"rounded_corner" |
"label_off" |
"text_rotate_vertical" |
"tab_unselected" |
"explore_off" |
"private_connectivity" |
"text_rotation_none" |
"satellite_alt" |
"not_accessible" |
"shop_2" |
"perm_camera_mic" |
"pin_invoke" |
"extension_off" |
"density_medium" |
"view_timeline" |
"pin_end" |
"text_rotate_up" |
"terminal" |
"text_rotation_angledown" |
"text_rotation_down" |
"text_rotation_angleup" |
"add_card" |
"swipe_left" |
"webhook" |
"123" |
"app_shortcut" |
"assured_workload" |
"html" |
"join_full" |
"swipe_right" |
"install_desktop" |
"swipe_up" |
"display_settings" |
"join_inner" |
"javascript" |
"swipe_down" |
"event_repeat" |
"install_mobile" |
"pan_tool_alt" |
"abc" |
"commit" |
"join_left" |
"data_thresholding" |
"output" |
"pinch" |
"density_small" |
"view_cozy" |
"swipe_vertical" |
"join_right" |
"view_kanban" |
"css" |
"swipe_right_alt" |
"view_comfy_alt" |
"view_compact_alt" |
"swipe_down_alt" |
"swipe_up_alt" |
"swipe_left_alt" |
"php" |
"density_large" |
"network_ping" |
"browse_gallery" |
"hls" |
"hls_off" |
"noise_control_off" |
"manage_history" |
"noise_aware" |
"spatial_audio_off" |
"spatial_tracking" |
"spatial_audio" |
"close" |
"menu" |
"expand_more" |
"arrow_back" |
"chevron_right" |
"arrow_forward_ios" |
"arrow_back_ios" |
"arrow_drop_down" |
"cancel" |
"more_vert" |
"chevron_left" |
"arrow_forward" |
"check" |
"expand_less" |
"more_horiz" |
"refresh" |
"apps" |
"payments" |
"arrow_upward" |
"east" |
"campaign" |
"arrow_back_ios_new" |
"arrow_downward" |
"arrow_right" |
"menu_open" |
"double_arrow" |
"fullscreen" |
"maps_home_work" |
"unfold_more" |
"arrow_drop_up" |
"west" |
"arrow_left" |
"south" |
"home_work" |
"north" |
"first_page" |
"fullscreen_exit" |
"north_east" |
"arrow_drop_down_circle" |
"last_page" |
"expand_circle_down" |
"unfold_less" |
"subdirectory_arrow_right" |
"legend_toggle" |
"south_east" |
"app_settings_alt" |
"assistant_direction" |
"subdirectory_arrow_left" |
"north_west" |
"waterfall_chart" |
"switch_left" |
"south_west" |
"switch_right" |
"pivot_table_chart" |
"apps_outage" |
"offline_share" |
"person" |
"notifications" |
"groups" |
"people" |
"share" |
"person_outline" |
"school" |
"person_add" |
"public" |
"emoji_events" |
"group" |
"notifications_active" |
"engineering" |
"construction" |
"people_alt" |
"group_add" |
"whatsapp" |
"psychology" |
"health_and_safety" |
"travel_explore" |
"emoji_emotions" |
"notifications_none" |
"sports_esports" |
"thumb_up_alt" |
"water_drop" |
"sentiment_satisfied" |
"location_city" |
"ios_share" |
"emoji_objects" |
"sentiment_very_satisfied" |
"precision_manufacturing" |
"person_add_alt" |
"military_tech" |
"science" |
"history_edu" |
"cake" |
"sentiment_dissatisfied" |
"coronavirus" |
"emoji_people" |
"sentiment_very_dissatisfied" |
"self_improvement" |
"person_remove" |
"poll" |
"female" |
"sports_soccer" |
"domain" |
"whatshot" |
"recommend" |
"people_outline" |
"mood" |
"male" |
"person_off" |
"masks" |
"workspace_premium" |
"sentiment_neutral" |
"person_add_alt_1" |
"connect_without_contact" |
"back_hand" |
"architecture" |
"hiking" |
"recycling" |
"notifications_off" |
"waving_hand" |
"luggage" |
"thumb_down_alt" |
"mood_bad" |
"front_hand" |
"emoji_nature" |
"catching_pokemon" |
"switch_account" |
"nights_stay" |
"emoji_symbols" |
"king_bed" |
"sports_basketball" |
"notification_add" |
"sports" |
"sports_kabaddi" |
"reduce_capacity" |
"sick" |
"emoji_food_beverage" |
"vaccines" |
"emoji_transportation" |
"interests" |
"social_distance" |
"transgender" |
"sports_tennis" |
"real_estate_agent" |
"deck" |
"elderly" |
"outdoor_grill" |
"clean_hands" |
"add_moderator" |
"follow_the_signs" |
"piano" |
"sanitizer" |
"plus_one" |
"fireplace" |
"surfing" |
"sports_motorsports" |
"add_reaction" |
"sports_handball" |
"cookie" |
"edit_notifications" |
"cruelty_free" |
"sports_baseball" |
"pages" |
"handshake" |
"sports_volleyball" |
"man" |
"heart_broken" |
"sports_football" |
"woman" |
"kayaking" |
"downhill_skiing" |
"skateboarding" |
"single_bed" |
"public_off" |
"personal_injury" |
"compost" |
"remove_moderator" |
"safety_divider" |
"notifications_paused" |
"person_remove_alt_1" |
"pix" |
"hive" |
"nordic_walking" |
"6_ft_apart" |
"sports_cricket" |
"sports_mma" |
"co2" |
"sports_golf" |
"paragliding" |
"group_off" |
"group_remove" |
"snowboarding" |
"party_mode" |
"kitesurfing" |
"snowshoeing" |
"ice_skating" |
"sports_rugby" |
"fitbit" |
"sports_hockey" |
"sledding" |
"scale" |
"south_america" |
"sports_martial_arts" |
"no_luggage" |
"piano_off" |
"boy" |
"domain_add" |
"girl" |
"elderly_woman" |
"sports_gymnastics" |
"scoreboard" |
"scuba_diving" |
"roller_skating" |
"sign_language" |
"cyclone" |
"thunderstorm" |
"landslide" |
"tsunami" |
"severe_cold" |
"flood" |
"volcano" |
"add" |
"add_circle_outline" |
"add_circle" |
"content_copy" |
"send" |
"clear" |
"mail" |
"save" |
"link" |
"filter_list" |
"remove" |
"inventory_2" |
"insights" |
"sort" |
"remove_circle_outline" |
"inventory" |
"bolt" |
"flag" |
"reply" |
"create" |
"add_box" |
"remove_circle" |
"push_pin" |
"block" |
"calculate" |
"undo" |
"how_to_reg" |
"content_paste" |
"file_copy" |
"report" |
"shield" |
"backspace" |
"archive" |
"save_alt" |
"policy" |
"tag" |
"change_circle" |
"redo" |
"content_cut" |
"forward" |
"inbox" |
"outlined_flag" |
"drafts" |
"link_off" |
"biotech" |
"ballot" |
"stacked_bar_chart" |
"markunread" |
"delete_sweep" |
"report_gmailerrorred" |
"square_foot" |
"stream" |
"where_to_vote" |
"add_link" |
"copy_all" |
"move_to_inbox" |
"waves" |
"dynamic_feed" |
"unarchive" |
"reply_all" |
"select_all" |
"low_priority" |
"text_format" |
"font_download" |
"weekend" |
"gesture" |
"upcoming" |
"how_to_vote" |
"attribution" |
"content_paste_search" |
"next_week" |
"content_paste_off" |
"content_paste_go" |
"save_as" |
"report_off" |
"font_download_off" |
"filter_list_off" |
"flag_circle" |
"deselect" |
"edit" |
"navigate_next" |
"photo_camera" |
"image" |
"picture_as_pdf" |
"tune" |
"circle" |
"receipt_long" |
"timer" |
"auto_stories" |
"navigate_before" |
"add_a_photo" |
"collections" |
"auto_awesome" |
"palette" |
"remove_red_eye" |
"music_note" |
"wb_sunny" |
"add_photo_alternate" |
"brush" |
"flash_on" |
"euro" |
"auto_fix_high" |
"control_point" |
"adjust" |
"looks_one" |
"style" |
"camera" |
"camera_alt" |
"straighten" |
"photo_library" |
"audiotrack" |
"portrait" |
"video_camera_front" |
"rotate_right" |
"grid_on" |
"color_lens" |
"crop_free" |
"crop_square" |
"timelapse" |
"landscape" |
"collections_bookmark" |
"slideshow" |
"lens" |
"panorama_fish_eye" |
"looks_two" |
"filter_drama" |
"auto_awesome_motion" |
"filter_vintage" |
"healing" |
"compare" |
"image_search" |
"crop" |
"rotate_left" |
"wb_incandescent" |
"looks_3" |
"blur_on" |
"center_focus_strong" |
"wb_cloudy" |
"flare" |
"dehaze" |
"face_retouching_natural" |
"auto_awesome_mosaic" |
"colorize" |
"filter_none" |
"brightness_4" |
"cases" |
"assistant" |
"nature_people" |
"filter_center_focus" |
"broken_image" |
"photo" |
"flash_off" |
"crop_original" |
"details" |
"brightness_5" |
"tag_faces" |
"brightness_6" |
"flip_camera_android" |
"grain" |
"loupe" |
"brightness_1" |
"flip" |
"flip_camera_ios" |
"movie_creation" |
"currency_rupee" |
"filter_1" |
"add_to_photos" |
"panorama" |
"image_not_supported" |
"center_focus_weak" |
"animation" |
"auto_fix_normal" |
"movie_filter" |
"view_comfy" |
"filter" |
"control_point_duplicate" |
"crop_din" |
"nature" |
"looks_4" |
"leak_add" |
"brightness_7" |
"photo_size_select_actual" |
"video_camera_back" |
"timer_off" |
"texture" |
"transform" |
"photo_camera_front" |
"incomplete_circle" |
"view_compact" |
"motion_photos_on" |
"rotate_90_degrees_ccw" |
"bedtime" |
"mic_external_on" |
"gradient" |
"looks_5" |
"music_off" |
"assistant_photo" |
"thermostat_auto" |
"exposure_plus_1" |
"photo_album" |
"hdr_strong" |
"shutter_speed" |
"filter_tilt_shift" |
"exposure" |
"filter_2" |
"hide_image" |
"looks" |
"vrpano" |
"crop_16_9" |
"flash_auto" |
"linked_camera" |
"blur_circular" |
"motion_photos_auto" |
"brightness_3" |
"looks_6" |
"brightness_2" |
"tonality" |
"wb_twilight" |
"iso" |
"photo_filter" |
"photo_size_select_small" |
"crop_rotate" |
"crop_portrait" |
"crop_7_5" |
"hdr_weak" |
"filter_hdr" |
"photo_size_select_large" |
"filter_3" |
"camera_front" |
"crop_5_4" |
"filter_frames" |
"exposure_zero" |
"camera_roll" |
"filter_b_and_w" |
"burst_mode" |
"blur_linear" |
"crop_3_2" |
"crop_landscape" |
"rotate_90_degrees_cw" |
"switch_camera" |
"switch_video" |
"filter_9_plus" |
"filter_7" |
"contrast" |
"photo_camera_back" |
"exposure_plus_2" |
"wb_iridescent" |
"motion_photos_paused" |
"grid_off" |
"filter_4" |
"monochrome_photos" |
"filter_5" |
"face_retouching_off" |
"auto_fix_off" |
"logo_dev" |
"leak_remove" |
"wb_shade" |
"timer_10" |
"exposure_neg_1" |
"panorama_photosphere" |
"filter_9" |
"currency_pound" |
"video_stable" |
"filter_8" |
"motion_photos_off" |
"blur_off" |
"hdr_on" |
"filter_6" |
"currency_yen" |
"panorama_horizontal" |
"vignette" |
"raw_on" |
"image_aspect_ratio" |
"camera_rear" |
"30fps_select" |
"dirty_lens" |
"timer_3" |
"motion_photos_pause" |
"60fps_select" |
"24mp" |
"panorama_wide_angle_select" |
"currency_bitcoin" |
"exposure_neg_2" |
"autofps_select" |
"panorama_photosphere_select" |
"currency_ruble" |
"panorama_horizontal_select" |
"panorama_wide_angle" |
"mic_external_off" |
"hdr_plus" |
"wb_auto" |
"panorama_vertical_select" |
"panorama_vertical" |
"hdr_enhanced_select" |
"12mp" |
"mp" |
"hevc" |
"23mp" |
"18mp" |
"raw_off" |
"hdr_off" |
"11mp" |
"20mp" |
"3mp" |
"17mp" |
"10mp" |
"13mp" |
"21mp" |
"19mp" |
"2mp" |
"4mp" |
"14mp" |
"22mp" |
"5mp" |
"8mp" |
"16mp" |
"15mp" |
"7mp" |
"9mp" |
"6mp" |
"deblur" |
"currency_lira" |
"currency_yuan" |
"currency_franc" |
"bedtime_off" |
"email" |
"location_on" |
"call" |
"phone" |
"business" |
"chat" |
"mail_outline" |
"vpn_key" |
"list_alt" |
"qr_code_scanner" |
"chat_bubble_outline" |
"alternate_email" |
"forum" |
"chat_bubble" |
"textsms" |
"contact_mail" |
"qr_code_2" |
"qr_code" |
"person_search" |
"sentiment_satisfied_alt" |
"message" |
"comment" |
"contacts" |
"app_registration" |
"import_contacts" |
"contact_phone" |
"live_help" |
"import_export" |
"forward_to_inbox" |
"rss_feed" |
"hourglass_bottom" |
"hourglass_top" |
"mark_email_read" |
"read_more" |
"key" |
"call_end" |
"mark_email_unread" |
"more_time" |
"document_scanner" |
"clear_all" |
"dialpad" |
"phone_enabled" |
"mark_chat_unread" |
"3p" |
"screen_share" |
"cancel_presentation" |
"call_made" |
"call_split" |
"hub" |
"unsubscribe" |
"present_to_all" |
"add_ic_call" |
"mark_chat_read" |
"stay_current_portrait" |
"domain_verification" |
"phonelink_ring" |
"call_received" |
"phonelink_lock" |
"duo" |
"phone_disabled" |
"ring_volume" |
"stay_primary_portrait" |
"phonelink_setup" |
"location_off" |
"swap_calls" |
"voicemail" |
"call_merge" |
"mobile_screen_share" |
"phonelink_erase" |
"person_add_disabled" |
"cell_wifi" |
"call_missed_outgoing" |
"domain_disabled" |
"speaker_phone" |
"stop_screen_share" |
"desktop_access_disabled" |
"call_missed" |
"print_disabled" |
"co_present" |
"pause_presentation" |
"dialer_sip" |
"invert_colors_off" |
"rtt" |
"wifi_calling" |
"portable_wifi_off" |
"spoke" |
"stay_current_landscape" |
"sip" |
"comments_disabled" |
"nat" |
"stay_primary_landscape" |
"no_sim" |
"cell_tower" |
"send_time_extension" |
"mark_unread_chat_alt" |
"key_off" |
"vpn_key_off" |
"file_download" |
"file_upload" |
"download" |
"folder" |
"grid_view" |
"upload_file" |
"cloud_upload" |
"text_snippet" |
"folder_open" |
"cloud" |
"request_quote" |
"cloud_download" |
"drive_file_rename_outline" |
"attachment" |
"upload" |
"download_for_offline" |
"create_new_folder" |
"downloading" |
"folder_shared" |
"cloud_done" |
"topic" |
"download_done" |
"cloud_queue" |
"approval" |
"cloud_off" |
"drive_file_move" |
"workspaces" |
"drive_folder_upload" |
"file_download_done" |
"newspaper" |
"attach_email" |
"rule_folder" |
"cloud_circle" |
"snippet_folder" |
"file_open" |
"file_download_off" |
"cloud_sync" |
"folder_zip" |
"drive_file_move_rtl" |
"folder_delete" |
"difference" |
"folder_copy" |
"folder_off" |
"format_overline" |
"local_shipping" |
"place" |
"menu_book" |
"local_offer" |
"map" |
"badge" |
"category" |
"restaurant" |
"directions_car" |
"volunteer_activism" |
"local_fire_department" |
"my_location" |
"local_mall" |
"flight" |
"near_me" |
"handyman" |
"directions_run" |
"restaurant_menu" |
"medical_services" |
"layers" |
"lunch_dining" |
"park" |
"local_hospital" |
"directions_walk" |
"celebration" |
"pin_drop" |
"local_library" |
"local_atm" |
"local_activity" |
"local_cafe" |
"delivery_dining" |
"rate_review" |
"person_pin" |
"directions_bike" |
"design_services" |
"fastfood" |
"directions_bus" |
"local_police" |
"directions_car_filled" |
"miscellaneous_services" |
"local_phone" |
"home_repair_service" |
"local_grocery_store" |
"zoom_out_map" |
"hotel" |
"cleaning_services" |
"navigation" |
"person_pin_circle" |
"directions" |
"money" |
"local_gas_station" |
"local_florist" |
"local_parking" |
"train" |
"local_post_office" |
"two_wheeler" |
"traffic" |
"alt_route" |
"electrical_services" |
"local_bar" |
"pedal_bike" |
"directions_boat" |
"beenhere" |
"agriculture" |
"add_business" |
"liquor" |
"360" |
"moving" |
"local_airport" |
"add_location_alt" |
"local_dining" |
"sailing" |
"maps_ugc" |
"ramen_dining" |
"local_taxi" |
"hail" |
"local_printshop" |
"local_pizza" |
"local_drink" |
"theater_comedy" |
"not_listed_location" |
"trip_origin" |
"local_laundry_service" |
"add_location" |
"dinner_dining" |
"bakery_dining" |
"diamond" |
"route" |
"directions_bus_filled" |
"transfer_within_a_station" |
"takeout_dining" |
"terrain" |
"wine_bar" |
"multiple_stop" |
"icecream" |
"local_pharmacy" |
"store_mall_directory" |
"museum" |
"nightlife" |
"emergency" |
"set_meal" |
"add_road" |
"local_see" |
"departure_board" |
"hardware" |
"festival" |
"plumbing" |
"electric_car" |
"edit_location" |
"ev_station" |
"car_rental" |
"attractions" |
"local_convenience_store" |
"layers_clear" |
"edit_road" |
"run_circle" |
"pest_control" |
"dry_cleaning" |
"edit_location_alt" |
"moped" |
"edit_attributes" |
"wrong_location" |
"car_repair" |
"satellite" |
"local_movies" |
"directions_boat_filled" |
"taxi_alert" |
"breakfast_dining" |
"tram" |
"atm" |
"brunch_dining" |
"transit_enterexit" |
"subway" |
"church" |
"hvac" |
"electric_bike" |
"electric_scooter" |
"factory" |
"directions_transit" |
"warehouse" |
"bus_alert" |
"forest" |
"local_car_wash" |
"soup_kitchen" |
"streetview" |
"local_hotel" |
"zoom_in_map" |
"compass_calibration" |
"directions_subway" |
"directions_railway" |
"electric_moped" |
"mode_of_travel" |
"electric_rickshaw" |
"castle" |
"railway_alert" |
"local_play" |
"no_meals" |
"bike_scooter" |
"egg" |
"snowmobile" |
"near_me_disabled" |
"connecting_airports" |
"pest_control_rodent" |
"directions_transit_filled" |
"mosque" |
"airline_stops" |
"no_transfer" |
"directions_subway_filled" |
"directions_railway_filled" |
"signpost" |
"airlines" |
"egg_alt" |
"temple_buddhist" |
"flight_class" |
"merge" |
"temple_hindu" |
"fort" |
"kebab_dining" |
"synagogue" |
"stadium" |
"turn_right" |
"u_turn_left" |
"fork_right" |
"straight" |
"turn_left" |
"u_turn_right" |
"roundabout_right" |
"turn_slight_left" |
"turn_sharp_right" |
"tire_repair" |
"turn_slight_right" |
"fork_left" |
"roundabout_left" |
"turn_sharp_left" |
"ramp_right" |
"ramp_left" |
"medical_information" |
"crisis_alert" |
"car_crash" |
"safety_check" |
"emergency_share" |
"sos" |
"emergency_recording" |
"no_crash" |
"screen_rotation_alt" |
"minor_crash" |
"play_arrow" |
"play_circle_filled" |
"videocam" |
"mic" |
"play_circle" |
"volume_up" |
"pause" |
"play_circle_outline" |
"volume_off" |
"replay" |
"skip_next" |
"library_books" |
"speed" |
"stop" |
"fiber_manual_record" |
"movie" |
"skip_previous" |
"new_releases" |
"playlist_add" |
"equalizer" |
"loop" |
"fast_forward" |
"web" |
"video_library" |
"playlist_add_check" |
"mic_off" |
"library_add" |
"video_call" |
"subscriptions" |
"pause_circle" |
"repeat" |
"shuffle" |
"volume_mute" |
"stop_circle" |
"not_interested" |
"mic_none" |
"sort_by_alpha" |
"library_music" |
"fast_rewind" |
"videocam_off" |
"volume_down" |
"queue_music" |
"pause_circle_filled" |
"web_asset" |
"recent_actors" |
"hearing" |
"subtitles" |
"library_add_check" |
"album" |
"note" |
"pause_circle_outline" |
"fiber_new" |
"av_timer" |
"games" |
"radio" |
"playlist_play" |
"replay_circle_filled" |
"branding_watermark" |
"queue" |
"forward_10" |
"replay_10" |
"closed_caption" |
"video_settings" |
"featured_play_list" |
"control_camera" |
"airplay" |
"add_to_queue" |
"slow_motion_video" |
"repeat_one" |
"hd" |
"call_to_action" |
"snooze" |
"playlist_add_check_circle" |
"repeat_on" |
"high_quality" |
"closed_caption_off" |
"replay_30" |
"featured_video" |
"5g" |
"shuffle_on" |
"forward_30" |
"music_video" |
"replay_5" |
"queue_play_next" |
"art_track" |
"forward_5" |
"hearing_disabled" |
"explicit" |
"playlist_add_circle" |
"4k" |
"fiber_smart_record" |
"video_label" |
"closed_caption_disabled" |
"repeat_one_on" |
"remove_from_queue" |
"surround_sound" |
"web_asset_off" |
"play_disabled" |
"playlist_remove" |
"sd" |
"interpreter_mode" |
"missed_video_call" |
"fiber_pin" |
"10k" |
"fiber_dvr" |
"video_file" |
"1k" |
"4k_plus" |
"audio_file" |
"2k" |
"8k" |
"1k_plus" |
"9k_plus" |
"8k_plus" |
"3k" |
"5k" |
"3k_plus" |
"7k_plus" |
"5k_plus" |
"9k" |
"2k_plus" |
"7k" |
"6k_plus" |
"6k" |
"star" |
"check_box" |
"check_box_outline_blank" |
"radio_button_unchecked" |
"radio_button_checked" |
"star_border" |
"toggle_on" |
"star_outline" |
"toggle_off" |
"star_half" |
"indeterminate_check_box" |
"star_purple500" |
"star_border_purple500" |
"warning" |
"error" |
"error_outline" |
"warning_amber" |
"notification_important" |
"add_alert" |
"auto_delete" |
"attach_money" |
"format_list_bulleted" |
"mode_edit" |
"monetization_on" |
"attach_file" |
"edit_note" |
"post_add" |
"bar_chart" |
"checklist" |
"drag_handle" |
"insert_drive_file" |
"show_chart" |
"format_quote" |
"format_list_numbered" |
"border_color" |
"table_chart" |
"pie_chart" |
"notes" |
"insert_photo" |
"format_bold" |
"text_fields" |
"insert_emoticon" |
"table_rows" |
"title" |
"mode" |
"auto_graph" |
"publish" |
"insert_chart_outlined" |
"mode_comment" |
"checklist_rtl" |
"query_stats" |
"insert_invitation" |
"mode_edit_outline" |
"insert_link" |
"functions" |
"format_italic" |
"format_align_left" |
"format_color_fill" |
"horizontal_rule" |
"add_comment" |
"insert_chart" |
"draw" |
"linear_scale" |
"format_size" |
"bubble_chart" |
"format_underlined" |
"stacked_line_chart" |
"money_off" |
"insert_comment" |
"vertical_align_bottom" |
"vertical_align_top" |
"format_align_center" |
"height" |
"format_paint" |
"format_color_text" |
"format_align_right" |
"area_chart" |
"scatter_plot" |
"merge_type" |
"format_list_numbered_rtl" |
"highlight" |
"schema" |
"format_align_justify" |
"add_chart" |
"format_shapes" |
"money_off_csred" |
"pie_chart_outline" |
"short_text" |
"align_horizontal_left" |
"format_indent_increase" |
"strikethrough_s" |
"vertical_align_center" |
"format_color_reset" |
"multiline_chart" |
"square" |
"numbers" |
"score" |
"border_all" |
"format_line_spacing" |
"format_indent_decrease" |
"format_clear" |
"data_object" |
"space_bar" |
"align_vertical_bottom" |
"horizontal_distribute" |
"align_horizontal_center" |
"align_horizontal_right" |
"format_strikethrough" |
"vertical_distribute" |
"superscript" |
"margin" |
"wrap_text" |
"subscript" |
"border_clear" |
"align_vertical_top" |
"align_vertical_center" |
"hexagon" |
"rectangle" |
"border_style" |
"padding" |
"candlestick_chart" |
"border_outer" |
"move_up" |
"data_array" |
"move_down" |
"text_increase" |
"line_axis" |
"format_textdirection_l_to_r" |
"border_left" |
"border_bottom" |
"border_inner" |
"pentagon" |
"border_horizontal" |
"format_textdirection_r_to_l" |
"polyline" |
"border_top" |
"border_right" |
"border_vertical" |
"insert_page_break" |
"text_decrease" |
"support_agent" |
"wifi" |
"account_tree" |
"sync" |
"event_available" |
"priority_high" |
"phone_in_talk" |
"event_note" |
"confirmation_number" |
"sms" |
"live_tv" |
"ondemand_video" |
"wifi_off" |
"event_busy" |
"drive_eta" |
"do_not_disturb_on" |
"wc" |
"more" |
"power" |
"do_not_disturb" |
"sync_problem" |
"time_to_leave" |
"vpn_lock" |
"do_disturb_on" |
"enhanced_encryption" |
"folder_special" |
"running_with_errors" |
"network_check" |
"sms_failed" |
"do_disturb" |
"phone_callback" |
"system_update" |
"adb" |
"personal_video" |
"voice_chat" |
"phone_forwarded" |
"power_off" |
"airline_seat_recline_normal" |
"vibration" |
"do_disturb_alt" |
"do_not_disturb_alt" |
"sync_disabled" |
"tap_and_play" |
"no_encryption" |
"sd_card" |
"phone_missed" |
"airline_seat_recline_extra" |
"mms" |
"imagesearch_roller" |
"disc_full" |
"bluetooth_audio" |
"no_encryption_gmailerrorred" |
"airline_seat_individual_suite" |
"sd_card_alert" |
"do_not_disturb_off" |
"sim_card_alert" |
"phone_paused" |
"phone_locked" |
"do_disturb_off" |
"airline_seat_flat" |
"network_locked" |
"phone_bluetooth_speaker" |
"airline_seat_flat_angled" |
"tv_off" |
"directions_off" |
"airline_seat_legroom_normal" |
"airline_seat_legroom_extra" |
"airline_seat_legroom_reduced" |
"sync_lock" |
"keyboard_arrow_down" |
"phone_iphone" |
"smartphone" |
"keyboard_arrow_right" |
"computer" |
"security" |
"smart_display" |
"desktop_windows" |
"phone_android" |
"keyboard_backspace" |
"keyboard_arrow_up" |
"laptop" |
"keyboard_arrow_left" |
"smart_toy" |
"headphones" |
"keyboard" |
"keyboard_return" |
"tv" |
"memory" |
"headset_mic" |
"point_of_sale" |
"keyboard_double_arrow_right" |
"mouse" |
"keyboard_voice" |
"developer_board" |
"videogame_asset" |
"router" |
"keyboard_double_arrow_left" |
"device_hub" |
"cast_for_education" |
"headset" |
"laptop_mac" |
"cast" |
"keyboard_double_arrow_down" |
"watch" |
"tablet_mac" |
"devices_other" |
"keyboard_tab" |
"keyboard_double_arrow_up" |
"desktop_mac" |
"laptop_chromebook" |
"phonelink" |
"monitor" |
"speaker" |
"toys" |
"gamepad" |
"keyboard_alt" |
"sim_card" |
"connected_tv" |
"start" |
"tablet_android" |
"cast_connected" |
"laptop_windows" |
"device_unknown" |
"keyboard_hide" |
"scanner" |
"tablet" |
"keyboard_capslock" |
"browser_updated" |
"earbuds" |
"speaker_group" |
"headset_off" |
"home_max" |
"headphones_battery" |
"smart_screen" |
"power_input" |
"dock" |
"browser_not_supported" |
"home_mini" |
"earbuds_battery" |
"phonelink_off" |
"developer_board_off" |
"videogame_asset_off" |
"keyboard_command_key" |
"adf_scanner" |
"keyboard_control_key" |
"keyboard_option_key" |
"watch_off" |
"light_mode" |
"restart_alt" |
"dark_mode" |
"task" |
"password" |
"summarize" |
"sell" |
"signal_cellular_alt" |
"devices" |
"settings_suggest" |
"quiz" |
"widgets" |
"storage" |
"battery_full" |
"credit_score" |
"thermostat" |
"gps_fixed" |
"price_check" |
"medication" |
"pin" |
"price_change" |
"tungsten" |
"gpp_good" |
"battery_charging_full" |
"reviews" |
"note_alt" |
"fmd_good" |
"air" |
"graphic_eq" |
"bluetooth" |
"dvr" |
"access_time" |
"nightlight" |
"sports_score" |
"water" |
"share_location" |
"gpp_maybe" |
"cable" |
"location_searching" |
"shortcut" |
"cameraswitch" |
"monitor_weight" |
"device_thermostat" |
"airplane_ticket" |
"battery_std" |
"signal_wifi_4_bar" |
"radar" |
"data_usage" |
"wallpaper" |
"monitor_heart" |
"gpp_bad" |
"developer_mode" |
"bloodtype" |
"wifi_tethering" |
"mode_night" |
"signal_cellular_4_bar" |
"network_wifi" |
"flashlight_on" |
"airplanemode_active" |
"splitscreen" |
"fmd_bad" |
"access_time_filled" |
"battery_alert" |
"mobile_friendly" |
"send_to_mobile" |
"sim_card_download" |
"lens_blur" |
"signal_wifi_statusbar_4_bar" |
"usb" |
"screen_search_desktop" |
"screen_rotation" |
"signal_wifi_statusbar_connected_no_internet_4" |
"system_security_update_good" |
"gps_not_fixed" |
"bluetooth_connected" |
"remember_me" |
"pattern" |
"battery_saver" |
"nfc" |
"play_lesson" |
"mode_standby" |
"network_cell" |
"brightness_high" |
"storm" |
"screenshot" |
"data_saver_off" |
"signal_wifi_0_bar" |
"brightness_low" |
"brightness_medium" |
"data_saver_on" |
"bluetooth_searching" |
"ad_units" |
"mobiledata_off" |
"bluetooth_disabled" |
"grid_4x4" |
"security_update_good" |
"signal_wifi_off" |
"hdr_auto" |
"battery_unknown" |
"signal_wifi_bad" |
"wifi_calling_3" |
"settings_system_daydream" |
"access_alarms" |
"aod" |
"signal_wifi_connected_no_internet_4" |
"add_to_home_screen" |
"signal_cellular_0_bar" |
"security_update" |
"flourescent" |
"gps_off" |
"4g_mobiledata" |
"flashlight_off" |
"access_alarm" |
"grid_3x3" |
"sd_storage" |
"wifi_lock" |
"reset_tv" |
"signal_wifi_statusbar_null" |
"brightness_auto" |
"do_not_disturb_on_total_silence" |
"signal_cellular_connected_no_internet_4_bar" |
"security_update_warning" |
"airplanemode_inactive" |
"nearby_error" |
"1x_mobiledata" |
"system_security_update" |
"signal_cellular_connected_no_internet_0_bar" |
"screen_lock_portrait" |
"system_security_update_warning" |
"discount" |
"wifi_tethering_off" |
"lan" |
"4g_plus_mobiledata" |
"edgesensor_high" |
"signal_wifi_4_bar_lock" |
"lte_mobiledata" |
"bluetooth_drive" |
"media_bluetooth_on" |
"location_disabled" |
"add_alarm" |
"signal_cellular_off" |
"signal_cellular_nodata" |
"signal_cellular_null" |
"mobile_off" |
"ssid_chart" |
"30fps" |
"screen_lock_rotation" |
"edgesensor_low" |
"grid_goldenratio" |
"punch_clock" |
"rsvp" |
"60fps" |
"lte_plus_mobiledata" |
"3g_mobiledata" |
"usb_off" |
"screen_lock_landscape" |
"timer_10_select" |
"medication_liquid" |
"g_mobiledata" |
"signal_cellular_no_sim" |
"timer_3_select" |
"h_mobiledata" |
"media_bluetooth_off" |
"e_mobiledata" |
"h_plus_mobiledata" |
"r_mobiledata" |
"wifi_password" |
"hdr_on_select" |
"hdr_auto_select" |
"hdr_off_select" |
"nearby_off" |
"phishing" |
"wifi_tethering_error" |
"wifi_find" |
"wifi_channel" |
"battery_5_bar" |
"battery_6_bar" |
"battery_4_bar" |
"battery_3_bar" |
"battery_0_bar" |
"wifi_2_bar" |
"network_wifi_1_bar" |
"network_wifi_2_bar" |
"network_wifi_3_bar" |
"battery_1_bar" |
"wifi_1_bar" |
"battery_2_bar" |
"signal_cellular_alt_1_bar" |
"signal_cellular_alt_2_bar" |
"devices_fold" |
"storefront" |
"apartment" |
"fitness_center" |
"business_center" |
"spa" |
"house" |
"meeting_room" |
"corporate_fare" |
"ac_unit" |
"cottage" |
"family_restroom" |
"other_houses" |
"checkroom" |
"grass" |
"all_inclusive" |
"airport_shuttle" |
"child_care" |
"pool" |
"beach_access" |
"kitchen" |
"holiday_village" |
"casino" |
"roofing" |
"room_service" |
"room_preferences" |
"sports_bar" |
"free_breakfast" |
"bathtub" |
"escalator_warning" |
"child_friendly" |
"food_bank" |
"gite" |
"villa" |
"foundation" |
"night_shelter" |
"golf_course" |
"microwave" |
"stairs" |
"backpack" |
"no_photography" |
"wash" |
"house_siding" |
"cabin" |
"elevator" |
"smoking_rooms" |
"countertops" |
"hot_tub" |
"water_damage" |
"fire_extinguisher" |
"charging_station" |
"soap" |
"rv_hookup" |
"carpenter" |
"umbrella" |
"baby_changing_station" |
"smoke_free" |
"tapas" |
"rice_bowl" |
"do_not_touch" |
"balcony" |
"no_food" |
"wheelchair_pickup" |
"fence" |
"houseboat" |
"bungalow" |
"iron" |
"bento" |
"chalet" |
"tty" |
"crib" |
"dry" |
"no_meeting_room" |
"escalator" |
"do_not_step" |
"no_drinks" |
"stroller" |
"no_cell" |
"no_flash" |
"no_backpack" |
"no_stroller" |
"vaping_rooms" |
"vape_free" |
"feed" |
"manage_search" |
"chair" |
"bed" |
"podcasts" |
"yard" |
"shower" |
"coffee" |
"window" |
"door_front" |
"light" |
"garage" |
"dining" |
"flatware" |
"coffee_maker" |
"blender" |
"camera_indoor" |
"bedroom_parent" |
"bathroom" |
"bedroom_baby" |
"chair_alt" |
"living" |
"door_back" |
"door_sliding" |
"camera_outdoor" |
"doorbell" |
"bedroom_child" |
"table_restaurant" |
"table_bar" |
"sensor_door" |
"sensor_window" |
"shield_moon";

export type IconSize = 18 | 24 | 36 | 48;

export type IconModifier = "light" | "dark";

export class IconDefinition {
    constructor(
        public readonly face: IconFace, 
        public readonly modifier: IconModifier = "light", 
        public readonly active: boolean = true,
        public readonly size: IconSize = 24) { }

    withModifier = (modifier: IconModifier) => new IconDefinition(this.face, modifier, this.active, this.size);
    
    withActive = (active: boolean) => new IconDefinition(this.face, this.modifier, active, this.size);

    withSize = (size: IconSize) => new IconDefinition(this.face, this.modifier, this.active, size);

    get css():string {
        return `material-icons md=${this.modifier} md-${this.size} ${!this.active && 'md-inactive'}` 
    }
}

export const Icons = {
    Search: new IconDefinition("search"),
    Home: new IconDefinition("home"),
    Account: new IconDefinition("account_circle"),
    Settings: new IconDefinition("settings"),
    Done: new IconDefinition("done")
};